name: Playwright MCP Tests CI

on:
  workflow_dispatch:
    inputs:
      environmentname:
        description: 'Environment'
        default: 'dev'
        required: true
      browsername:
        description: 'Choose Browser'
        # Expecting one of: chromium, chrome, chrome-beta, msedge, msedge-beta, msedge-dev, firefox, webkit
        default: 'chromium'
        required: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      shell: bash
      run: |
        if [ -n "${{ github.event.inputs.browsername }}" ]; then
          echo "Installing only ${{ github.event.inputs.browsername }} browser with dependencies."
          npx playwright install --with-deps ${{ github.event.inputs.browsername }}
        else
          echo "Installing all browsers with dependencies as no specific browsername was provided."
          npx playwright install --with-deps
        fi
    - name: Run Playwright tests
      shell: bash
      run: |
        if [ -n "${{ github.event.inputs.browsername }}" ]; then
          echo "Running Playwright tests with project: ${{ github.event.inputs.browsername }}"
          npx playwright test --project=${{ github.event.inputs.browsername }}
        else
          echo "Running Playwright tests for all configured projects (or default)."
          npx playwright test
        fi
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
