name: Playwright MCP Tests CI

on:
  workflow_dispatch:
    inputs:
      environmentname:
        description: 'Environment'
        default: 'dev'
        required: true
      browsername:
        description: 'Choose Browser'
        default: 'chromium'
        required: true
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, World!

      - name: Run multi-line script
        run: 
          echo "You requested running ${{ github.event.inputs.environmentname }} tests"
          echo "Inside the ${{ github.event.inputs.browsername }} browser"
